### ISSUE TITLE
Add all contributors bot

### ISSUE THREAD

**Issue by griff-rees** [Living-with-machines/lwmdb#125]
- [x] Enable automating this
- [x] Align that with Zenodo
- [x] Add `allcontributors` to README.md
- [ ] Add documentation for applying this

**Comment by AoifeHughes** [comment]
https://github.com/all-contributors
please add @ChristinaLast for code, ideas, planning.
please add @thobson88 for code, ideas, planning.
please add @npedrazzini for code, ideas, planning.
please add @kasparvonbeelen for code, ideas, planning.
please add @mcollardanuy for code, ideas, planning.
please add @kmcdono2 for code, ideas, planning.
please add @andrewphilipsmith for code, ideas, planning.
please add @mialondon for ideas, planning.
please add @claireaustin01 for ideas, planning
please add @AoifeHughes for code, ideas.

**Comment by AoifeHughes** [comment]
@all-contributors
please add @ChristinaLast for code, ideas, planning.
please add @thobson88 for code, ideas, planning.
please add @npedrazzini for code, ideas, planning.
please add @kasparvonbeelen for code, ideas, planning.
please add @mcollardanuy for code, ideas, planning.
please add @kmcdono2 for code, ideas, planning.
please add @andrewphilipsmith for code, ideas, planning.
please add @mialondon for ideas, planning.
please add @claireaustin01 for ideas, planning
please add @AoifeHughes for code, ideas.

**Comment by AoifeHughes** [comment]
@all-contributors
please add @ChristinaLast for code, ideas, planning.
please add @thobson88 for code, ideas, planning.
please add @npedrazzini for code, ideas, planning.
please add @kasparvonbeelen for code, ideas, planning.
please add @mcollardanuy for code, ideas, planning.
please add @kmcdono2 for code, ideas, planning.
please add @andrewphilipsmith for code, ideas, planning.
please add @mialondon for ideas, planning.
please add @claireaustin01 for ideas, planning
please add @AoifeHughes for code, ideas.

**Comment by AoifeHughes** [comment]
@griff-rees I think us trying to merge this in has broken it. I wonder if it's just easier at this point to remove it and just start from scratch with 1 person to begin with?

**Comment by AoifeHughes** [comment]
Testing adding just me so I don't ping people too much:

**Comment by AoifeHughes** [comment]
@all-contributors please add @AoifeHughes for code

**Comment by AoifeHughes** [comment]
@all-contributors please add @AoifeHughes for code

**Comment by AoifeHughes** [comment]
@all-contributors
please add @ChristinaLast for code, ideas, planning.
please add @thobson88 for code, ideas, planning.
please add @npedrazzini for code, ideas, planning.
please add @kasparvonbeelen for code, ideas, planning.
please add @mcollardanuy for code, ideas, planning.
please add @kmcdono2 for code, ideas, planning.
please add @andrewphilipsmith for code, ideas, planning.
please add @mialondon for ideas, planning.
please add @claireaustin01 for ideas, planning

**Comment by AoifeHughes** [comment]
☠️

**Comment by AoifeHughes** [comment]
@all-contributors please add @ChristinaLast for code, ideas, planning.

**Comment by AoifeHughes** [comment]
@all-contributors please add @thobson88 for code, ideas, planning.

**Comment by AoifeHughes** [comment]
@all-contributors please add @kasparvonbeelen for code, ideas, planning.

**Comment by AoifeHughes** [comment]
Okay, lets test all the PR's that I just squished have worked and allow for more additions

**Comment by AoifeHughes** [comment]
@all-contributors please add please add @DavidBeavan for code, ideas, planning.

**Comment by AoifeHughes** [comment]
@all-contributors please add please add @DavidBeavan for code, ideas, planning.

**Comment by AoifeHughes** [comment]
@griff-rees for future ref, do one at a time, way easier than trying to merge the conflicts!

**Comment by griff-rees** [comment]
Thanks again @AoifeHughes. I figure some aspects of this *aren't* automated, but some is? May split that to a separate ticket. Otherwise: think we can close this...

**Comment by AoifeHughes** [comment]
It’s semi automated. We need to add to the contributions guidelines for people to tag the bot in an issue. Eg, here.

**Comment by griff-rees** [comment]
Ah *now* I've clocked: https://allcontributors.org/docs/en/bot/usage

Sorry I didn't read that right the first time. So all the ticket comments of the form below are the semi-automation:

```
@all-contributors please add @<username> for <contributions>
```

And making clear what the list of potential `<contributions>` are is the crucial bit, that we could then append with custom types following from the documentation [configuration](https://allcontributors.org/docs/en/bot/configuration):

```json
"types": {
  "custom": {
    "symbol": "🔭",
    "description": "A custom contribution type.",
    "link": "[<%= symbol %>](<%= url %> \"<%= description %>\"),"
   }
}
```

**Comment by griff-rees** [comment]
See https://github.com/Living-with-machines/lwmdb/pull/172 for initial documentation.
