### ISSUE TITLE
command for cloning repo doesn't work

### ISSUE THREAD

**Issue by kmcdono2** [Living-with-machines/lwmdb#178]
should it be `git clone https://github.com/Living-with-machines/lwmdb.git`?

**Comment by griff-rees** [comment]
`git clone git@github.com:Living-with-machines/lwmdb.git` works fine for me and tends to provide a full checkout (not just the `main` branch). That may be contingent on me having commit access to the repository via my `GitHub` account though.

I used to have issues with `https` checkouts but this has changed a lot over the years (see https://stackoverflow.com/a/11041782/678486) and it does seem like `https` has gotten easier. Happy to switch the documentation to reflect that.

**Comment by griff-rees** [comment]
Hope the edits to `README.md` are ok @kmcdono2. Some other build issues came up with that fix so it seemed safe to merge. Obviously feel free to request more changes.

**Comment by kmcdono2** [comment]
Thanks @griff-rees - I'll have another go at getting it up and running next week!!
